format = """
[╭╼═╾ $username ╼═╾ $hostname ╼─╼─╼─╼─╼─╼─╼─╼─╼─╼─╼─](yellow) $cmd_duration
[╞╾ ](yellow)$directory$git_branch$git_commit$git_state$git_status$hg_branch
[╰╾](yellow) $character"""

[directory]
truncation_length = 2
truncation_symbol = " "
style = "bold #7abef5"
read_only = ""
disabled = false

[username]
style_user = "bold #ff9e4f"
style_root = "bold #eb4972"
show_always = true
format = "[$user]($style)"
disabled = false

[hostname]
ssh_only = false
format = "[$hostname]($style)"
trim_at = "."
style = "bold yellow"
disabled = false

[character]
success_symbol = "[◈](bold yellow)"
error_symbol = "[◈](bold red)"
disabled = false

[cmd_duration]
min_time = 420
show_milliseconds = false
format = "[$duration](bold yellow)"
disabled = false

[git_branch]
truncation_length = 12
style = "bold #b0d0eb"
truncation_symbol = "..."
disabled = false

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "
tag_disabled = false
only_detached = true

[git_status]
format = '([\[$conflicted$stashed$modified$staged$untracked$renamed$deleted$ahead$diverged$behind\]]($style) )'
conflicted = "ﲅ "
stashed = " "
modified = " "
staged = '[ $count ](bold green)'
untracked = '[‍ $count](bold #f0dd86)'
renamed = " "
deleted = " "
ahead = '[ ${count}](bold #57d9c3)'
diverged = '[ ](bold purple)'
behind = '[丹 ${count}](bold #eb4972)'

style = "bold #cedeeb"